sudo: required
addons:
  apt:
    packages:
    - docker-ce
  sonarcloud:
    organization: echoffee-github
services:
- docker
dist: trusty
language:
- python
- node_js
python:
- '3.3'
node_js:
- iojs
- '7'
before_install:
- sudo /etc/init.d/mysql stop
- pwd
- ls -la
- sudo docker-compose up -d
- docker --version
- pip install selenium
- pip install mysql-connector
script:
- sonar-scanner
- echo "Waiting a bit before pinging the containers..."
- sleep 15
- curl localhost:8080
- curl localhost:4444
- curl localhost:8081
- echo "Starting DB tests..."
- sh execute_tests_db.sh
- echo "Installing Node dependencies..."
- npm install nightwatch sha1 mysql
- echo "Starting E2E tests..."
- sh execute_tests_e2e.sh
before_deploy:
- sudo apt install zip
- zip haisau.zip -r src/* config/* docker/* LICENSE README.md docker-compose.yml
deploy:
  provider: releases
  api_key:
    secure: j0sKfjJcF084fKCtTx48pArfEppQxfhnuQxcPRKAI/CbMLa1yIBgDc9m97w/muheZdFsgeyZcJHRD9gJ+JEHSpI4Oi6NoN8wTkKXdx3uxvwj4D+1a7UBCVzZZCkzJIrEWJ0srZA9d55xKM+mazEG2WrVe8YgIKpddaf+KbTlUtyNERdHLfiZAu86houUkUHejccJFbI9M3IRIMkflUx9BCK29X32zkW/tOCL1Zq7eAVgx0T0YajyKX5frSMgj1QgVkTObDxyF2Zn+61j1pHKQSHPJDW8qFTL4HV9VPxCBHHD5iLzZ1wvOTrFEyywGw9noohd4HBshJqEgR5LzSUfqQgrpxXIiHlkqkQKLDBHCJYxj/FSkQfVqNp0KvjhkbFaCWPts122PdbQRbfjdkcdtJOumOOkS7RFoGIwMueCRg5hIt+iPHZD5xYKcmEDE0MuOQYXzT1asLjfzeD1S+kN9Ffej05xa5UDuRsCeUq9RD3G0o5YA7HlYUoho2rFfn0R7jvMdugKUK0u9RkyJxKJb0OF4laF6zvz0VojmLj5jpEc9e+rosoI2MRpwbqL/OQ9vPLi9D526qKL714JldPUTBaoWywtlb2Cpu8eAhbTwCIdDJySxdTjitOBsY4EGiMcCvBDIXVSucSAQ2AK9abWk3/yrBv6NZBViH11N/NG3ZM=
  file: haisau.zip
  on:
    tags: true
    repo: echoffee/haisau
