sudo: required
addons:
  apt:
    packages:
      - docker-ce

services:
        - docker

language: 
        - python
        - node_js
python:
        - "3.3"
node_js:
        - "iojs"
        - "7"
before_install:
        - sudo /etc/init.d/mysql stop
        - pwd
        - ls -la
        - sudo docker-compose up -d
        - docker --version
        - pip install selenium
        - pip install mysql-connector

script :
                - echo "Waiting a bit before pinging the containers..."
                - sleep 15
                - curl localhost:8080
                - curl localhost:4444
                - curl localhost:8081
                - echo "Starting tests..."
                - sh execute_db.sh
                - echo "Installing Nightwatch..."
                - npm install nightwatch
                - echo "Starting nightwatch tests..."
                - sh execute_e2e.sh
