module.exports = {
    'Modify Project' : function (client) {
        client
            .url("http://webserver:80/index.php")
            .pause(1000)
            .setValue("input[name='username']", "TestUser")
            .setValue("input[name='password']", "KaedeTakagaki")
            .click("button[name='login_user']")
            .pause(1000)
            .url("http://webserver:80/projectList.php")
            .waitForElementVisible("body", 1000)
            .assert.elementPresent("a[href*='modifyProject'][name*='T6DummyProject']")
            .click("a[href*='modifyProject'][name*='T6DummyProject']")
            .pause(1000)
            //.url(function (res) {console.log(res.value);})
            .assert.containsText("h1", "Modify project T6DummyProject")
            .setValue("input[name='projectName']", "T6DummyProjectEdited")
            .click("input[id='bCreate']")
            .pause(1000)
            //.url(function (res) {console.log(res.value);})
            //.source(function (res) {console.log(res.value);})
            .assert.elementPresent("a[href*='modifyProject'][name*='T6DummyProjectEdited']") 
            .click("a[href*='modifyProject'][name*='T6DummyProjectEdited']")
            .pause(1000)
            .click("a")
            .pause(1000)
            .assert.title("Project List")
            .assert.elementPresent("a[href*='modifyProject'][name*='T6DummyProjectEdited']") 
            .click("a[href*='modifyProject'][name*='T6DummyProjectEdited']")
            .pause(1000)
            .setValue("input[name='projectName']", "")
            .click("input[id='bCreate']")
            .pause(1000)
            .assert.containsText("a", "Go back")
            .click("a")
            .pause(1000)
            .assert.urlContains("modifyProject.php")
            .assert.containsText("h1", "T6DummyProjectEdited")
            .click("a")
            .pause(1000)
            .assert.urlContains("projectList.php")
            .assert.elementPresent("a[href*='modifyProject'][name*='T6DummyProjectEdited']") 
            .end()
    }
};
